name: demo-gtk-common-themes
version: current
summary: A demonstration application featuring the gtk-common-themes content snap
description: |
  This snap contains the gtk3-demo application, using theme data
  provided by one or more external snaps.

  Refer the following forum topic for more information:

      How to use the system GTK theme via the gtk-common-themes snap - doc - snapcraft.io
      https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235

grade: stable
confinement: strict

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

slots:
  gtk-app-dbus-svc:
    interface: dbus
    bus: session
    name: org.gtk.Demo2

plugs:
  # For file picker demo
  avahi-observe: # Non-A/C
  home:
  mount-observe: # Non-A/C
  removable-media: # Non-A/C

  # Common graphical application resources
  desktop:
  desktop-legacy:
  unity7:
  wayland:
  x11:

  # On a Wayland session, GTK instead uses the GSettings API to read the users preferences directly, bypassing the display server. So plugging the gsettings interface is also necessary.
  # Allowing GTK to detect the selected system theme - How to use the system GTK theme via the gtk-common-themes snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:

  # For sound theme demo
  pulseaudio:

  # For OpenGL demo
  opengl:

apps:
  demo-gtk-common-themes:
    command: >
      bin/desktop-launch
      $SNAP/usr/bin/gtk3-demo

parts:
  desktop-gtk3:
  demo:
    plugin: nil
    stage-packages:
    - gtk-3-examples

    # Temporary workaround for Bug #1776807 “`nil` plugin shouldn't pull anything to the srctre...” : Bugs : Snapcraft
    # https://bugs.launchpad.net/snapcraft/+bug/1776807
    override-pull: 'true'

    override-build: |
      set -ex
      snapcraftctl build
      mkdir -p \
        $SNAPCRAFT_PART_INSTALL/share/icons \
        $SNAPCRAFT_PART_INSTALL/share/sounds \
        $SNAPCRAFT_PART_INSTALL/share/themes
    stage:
    - usr
    - share/icons
    - share/themes
    - share/sounds
